/**:
    ros__parameters:
        use_imu_as_input: False                             # Change to True to use IMU as input of Point-LIO
        prop_at_freq_of_imu: True
        check_satu: True
        init_map_size: 20                                   # 增加初始地图大小，提高初始化稳定性
        point_filter_num: 4                                 # Options: 4, 3
        space_down_sample: True
        filter_size_surf: 0.3                               # 减小滤波尺寸，保留更多特征 (原0.5)
        filter_size_map: 0.3                                # 减小地图滤波尺寸 (原0.5)
        ivox_nearby_type: 18                                # 增加邻近点搜索数量 (原6)
        runtime_pos_log_enable: True                        # 启用运行时位置日志

        common:
            lid_topic: "livox/lidar"
            imu_topic: "livox/imu"
            con_frame: False                                # True: if you need to combine several LiDAR frames into one
            con_frame_num: 1                                # the number of frames combined
            cut_frame: False                                # True: if you need to cut one LiDAR frame into several subframes
            cut_frame_time_interval: 0.1                    # should be integral fraction of 1 / LiDAR frequency
            time_diff_lidar_to_imu: 0.0                     # Time offset between LiDAR and IMU calibrated by other algorithms, e.g., LI-Init (find in Readme)

        prior_pcd:
            enable: False
            prior_pcd_map_path: ""
            init_pose: [ 0.0, 0.0, 0.0 ]

        preprocess:
            lidar_type: 1                                   # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR
            scan_line: 4
            timestamp_unit: 3                               # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
            blind: 0.3                                      # 减小盲区，获取更多近距离特征 (原0.5)

        mapping:
            imu_en: True
            extrinsic_est_en: True                          # 启用外参在线估计 (原False)
            imu_time_inte: 0.005                            # = 1 / frequency of IMU
            lidar_time_inte: 0.1
            satu_acc: 3.0                                   # the saturation value of IMU's acceleration. not related to the units
            satu_gyro: 35.0                                 # the saturation value of IMU's angular velocity. not related to the units
            acc_norm: 9.81                                  # 修改为m/s^2单位 (原1.0)
            lidar_meas_cov: 0.001                           # 减小LiDAR噪声 (原0.01)
            acc_cov_output: 200.0                           # 减小加速度协方差 (原500.0)
            gyr_cov_output: 500.0                           # 减小陀螺仪协方差 (原1000.0)
            b_acc_cov: 0.00001                              # 减小加速度偏置协方差 (原0.0001)
            b_gyr_cov: 0.00001                              # 减小陀螺仪偏置协方差 (原0.0001)
            imu_meas_acc_cov: 0.1                           # 增加IMU加速度测量噪声 (原0.01)
            imu_meas_omg_cov: 0.05                          # 增加IMU角速度测量噪声 (原0.01)
            gyr_cov_input: 0.01                             # for IMU as input model
            acc_cov_input: 0.1                              # for IMU as input model
            plane_thr: 0.05                                 # 降低平面阈值，提高匹配精度 (原0.1)
            match_s: 81.0
            ivox_grid_resolution: 1.0                       # 减小网格分辨率，提高精度 (原2.0)
            gravity: [ 0.0, 0.0, -9.810 ]                   # [0.0, 9.810, 0.0] # gravity to be aligned
            gravity_init: [ 0.0, 0.0, -9.810 ]              # [0.0, 9.810, 0.0] # # preknown gravity in the first IMU body frame, use when imu_en is False or start from a non-stationary state
            extrinsic_T: [ -0.011, -0.02329, 0.04412 ]      # 需要根据实际标定结果调整
            extrinsic_R: [ 1.0, 0.0, 0.0,
                           0.0, 1.0, 0.0,
                           0.0, 0.0, 1.0 ]

        odometry:
            publish_odometry_without_downsample: False

        publish:
            path_en: True                                   # False: close the path output
            scan_publish_en: True                           # False: close all the point cloud output
            scan_bodyframe_pub_en: True                     # 启用body frame输出用于调试 (原False)
            tf_send_en: True                                # True: send transform from 'camera_init' to 'aft_mapped'

        pcd_save:
            pcd_save_en: False
            interval: -1                                    # how many LiDAR frames saved in each pcd file;
                                                            # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames. 